#!/usr/bin/env bash

javac -classpath postgresql-42.2.2.jar:. App.java

if [ -d world ]; then
    echo "[SYNC] persist begin"
    java -classpath postgresql-42.2.2.jar:. App persist
    echo "[SYNC] persist complete"
else
    echo "[SYNC] restore begin"
    java -classpath postgresql-42.2.2.jar:. App restore
    echo "[SYNC] restore complete"
fi

